name: solubility-paper-Lindberg_etal-2023
dependencies:
  - numpy
  - plotly
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - pip:
    - polars
    - pyarrow
    - openpyxl
    - plotly
